Make the port names compatible with Istio
AdWerx/charts pull request #34
Opened 2021-11-22 20:31 UTC by Amandeepsinghghai

#### What this PR does / why we need it: 
Makes the port names compatible with Istio.

Right now the if the helm chart is deployed in an istio enabled cluster, it fails to register the service as a part of the mesh because of https://istio.io/latest/docs/reference/config/analysis/ist0118/.

Reference - https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

PS: Thanks for your work on the helm chart. Really appreciate it 😃

2021-11-22 22:14 UTC, jbielick requested changes

2021-11-22 22:14 UTC, jbielick commented on faktory/templates/ui-service.yaml
> +      name: http-ui
This will need to be updated in the `ingress` as well

2021-11-22 22:14 UTC, jbielick commented on faktory/templates/server-service.yaml
> +      name: tcp-server
Should `name: metrics` be changed as well on line 20?

2021-11-25 06:26 UTC, Amandeepsinghghai commented
@jbielick I have made the requested changes. LMK if they are correct or some additional changes are required to get this PR merged

2021-11-25 11:47 UTC, jbielick commented on faktory/templates/server-service.yaml
> +      name: tcp-metrics
I believe this is an http endpoint

2021-11-26 03:26 UTC, Amandeepsinghghai commented on faktory/templates/server-service.yaml
> +      name: tcp-metrics
done

2021-11-29 16:52 UTC, merged

2021-11-29 16:54 UTC, jbielick commented
`v0.12.1` published